hrmain/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'hrtools'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^config/password', views.PasswordChangeView.as_view(), name='password_config'),
    url(r'^config/settings', views.UserSettingsView.as_view(), name='user_settings'),
]

hrmain/models.py
from django.db import models

# Create your models here.

hrmain/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm

class UserPasswordForm(PasswordChangeForm):
    pass

class UserSettingsForm(forms.Form):
    login = forms.CharField(required=False, max_length=50)
    email = forms.EmailField(required=False, max_length=50)
    first_name = forms.CharField(required=False, max_length=50)
    last_name = forms.CharField(required=False, max_length=50)
    password = forms.CharField(widget=forms.PasswordInput())
    pass

hrmain/views.py
from django.views import generic
from .forms import UserPasswordForm, UserSettingsForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms.utils import ErrorList
from django.contrib.auth.models import User
from django.contrib import messages
from django.shortcuts import redirect, reverse

class IndexView(generic.TemplateView):
    template_name = 'hrmain/base.html'
    context_object_name = 'index'
    
    def dispatch(self, request, *args, **kwargs):
        #Redirecting to url which was entered before login
        for next in ['next', 'redirect_to']:
            if next in self.request.GET:
                self.request.session['next'] = self.request.GET[next]
        if self.request.user.is_authenticated and 'next' not in self.request.session:
            return redirect(reverse('skillsearch:employees'))
        return super(IndexView, self).dispatch(request, *args, **kwargs)

class UserSettingsView(LoginRequiredMixin, generic.FormView):
    template_name = 'hrmain/settings.html'
    form_class = UserSettingsForm
    success_url = 'settings'
    login_url = '/'
    
    def form_valid(self, form):
        self.user = User.objects.get(id=self.request.user.id)
        if self.user.check_password(self.request.POST['password']):
            if self.request.POST['login']:
                self.user.username = self.request.POST['login']
            if self.request.POST['email']:
                self.user.email = self.request.POST['email']
            if self.request.POST['first_name']:
                self.user.first_name = self.request.POST['first_name']
            if self.request.POST['last_name']:
                self.user.last_name = self.request.POST['last_name']
            self.user.save()
            messages.success(self.request, 'Settings have been saved')
        else:
            #Throwing custom error for field and triggering form_invalid to show the error
            form.add_error('password', 'Password is invalid')
            return self.form_invalid(form)
        return super(UserSettingsView, self).form_valid(form)

class PasswordChangeView(LoginRequiredMixin, generic.FormView):
    template_name = 'hrmain/password.html'
    form_class = UserPasswordForm
    success_url = '/'
    login_url = '/'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'user': self.request.user, })
        return kwargs

    def form_valid(self, form):
        user = User.objects.get(id=self.request.user.id)
        user.set_password(self.request.POST['new_password2'])
        user.save()
        messages.success(self.request, 'Password has been changed')
        return super(PasswordChangeView, self).form_valid(form)

hrmain/templates/hrmain/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="../../../../favicon.ico">

        <title>HRTOOLS{% block title %}{% endblock %}</title>

        <!-- Bootstrap core CSS -->
        <link href="{% static 'hrmain/css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- Font Awesome icons -->
        <link rel="stylesheet" href="{% static 'hrmain/css/font-awesome.min.css' %}">

        <!-- Favicon -->
        <link rel="shortcut icon" type="image/png" href="{% static 'hrmain/cube.png' %}"/>

        <!-- Custom styles for this template -->
        <link href="{% static 'hrmain/css/style.css' %}" rel="stylesheet">
        {% block style %}
        {% endblock %}
        {% block javascript %}
            <script>
                window.onload = function() {
                    $('#login-button').popover({
                        html: true,
                        content: $('#login-form').html()
                    });
                }
            </script>
        {% endblock %}
    </head>

    <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="{% url 'hrtools:index' %}">{% block application_name %}HRTOOLS{% endblock %}</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#hrmain-navbar" aria-controls="hrmain-navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="hrmain-navbar">
            {% if user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Skillsearch
                    </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'skillsearch:employees' %}">Employees</a>
                    <a class="dropdown-item" href="{% url 'skillsearch:candidates' %}">Candidates</a>
                </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'hrtools:user_settings' %}">Configuraton</a>
                </li>
                {% if user.is_staff %}
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" id="logout-button" href="{% url 'hrlogin:logout' %}" data-toggle="popover" data-placement="bottom">Logout</a>
                </li>
            </ul>
            {% else %}
                {% include "hrmain/unlogged_menu.html" %}
            {% endif %}
        </div>

        {% block nav_form_right %}
        {% endblock %}

    </nav>

            {% block sidebar %}
            {% endblock %}

            {% block body %}
            <div class="container-fluid col-sm-9 col-md-10">

                <div class="body-template base-body">
                    <h1>This is the main page.</h1>
                    <p class="lead">There will be something, but now there is nothing.</p>
                </div>

            </div><!-- /.container -->

            {% endblock %}

        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
<!--<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>-->
<script src="{% static 'hrmain/js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'hrmain/js/popper.min.js' %}" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="{% static 'hrmain/js/bootstrap.min.js' %}"></script>
    </body>
</html>

hrmain/templates/hrmain/config_sidebar.html
<div class="col-md-3">
    <div class="nav flex-column nav-pills border rounded" id="v-pills-tab" role="tablist" aria-orientation="vertical">
        <a class="nav-link" id="v-pills-settings" href="{% url 'hrtools:user_settings' %}">Settings</a>
        <a class="nav-link" id="v-pills-password" href="{% url 'hrtools:password_config' %}">Change password</a>
    </div>
</div>

hrmain/templates/hrmain/password.html
{% extends "hrmain/settings_base.html" %}
{% load static %}

{% block settings_onload %}
    $('#v-pills-password').addClass('active')
{% endblock %}

{% block form %}
    <form action="{% url 'hrtools:password_config' %}" method="post">{% csrf_token %}
        {% include 'hrmain/setting_form.html' %}
    </form>
{% endblock %}

hrmain/templates/hrmain/setting_form.html
{% load hrmain_tags %}
{% for field in form %}
    <div class="form-group">
        {% for error in field.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
        <label for="{{ field.id }}">{{ field.label }}{% if field.field.required %}<span class="badge badge-light badge-secondary">required</span>{% endif %}</label>
        <input type="{{ field.field.widget.input_type }}" name="{{ field.name }}" \
               id="{{ field.id }}" class="form-control" placeholder="{{ field.label }}" \
               value="{% if  request.POST|get_dict_key:field.name %}{{ request.POST|get_dict_key:field.name }}{% endif %}">
    </div>
{% endfor %}
<button type="submit" class="btn btn-primary float-right">Submit</button>

hrmain/templates/hrmain/settings.html
{% extends "hrmain/settings_base.html" %}
{% load static %}

{% block settings_onload %}
    $('#v-pills-settings').addClass('active')
{% endblock %}

{% block form %}
    <form action="{% url 'hrtools:user_settings' %}" method="post">{% csrf_token %}
        {% include 'hrmain/setting_form.html' %}
    </form>
{% endblock %}

hrmain/templates/hrmain/settings_base.html
{% extends "hrmain/base.html" %}
{% load static %}

{% block javascript %}
        <script>
        window.onload = function() {
            $(".settings-success").fadeOut(3000)
            {% block settings_onload %}{% endblock %}
        }
    </script>
{% endblock %}

{% block title %}|Configuration{% endblock %}

{% block body %}
    <div class="container-fluid col-sm-9 col-md-10">
        <div class="body-template">
            {% for message in messages %}
                <div class="alert alert-success settings-success mx-auto" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
            <div class="row">
                {% include "hrmain/config_sidebar.html" %}
                <div class="col-md-1"></div>
                <div class="col-md-4 offset-md-4">
                    {% block form %}{% endblock %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

hrmain/templates/hrmain/unlogged_menu.html
<ul class="navbar-nav ml-auto">
    <li class="nav-item dropdown">
        <a class="nav-link" id="login-button" href="#" data-toggle="popover" data-placement="bottom">Login</a>
    </li>
</ul>
<div id="login-form" class="hide">
    <form action="{% url 'hrlogin:login' %}" method="post">
        {% csrf_token %}
      <div class="form-group">
        <label for="login-form-login">Login</label>
        <input type="text" class="form-control" name="username" id="login-form-login" aria-describedby="emailHelp" placeholder="Your login">
      </div>
      <div class="form-group">
        <label for="login-form-password">Password</label>
        <input type="password" class="form-control" id="login-form-password" name="password" placeholder="Your password">
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>