skillsearch/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView
from . import views


app_name = 'skillsearch'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(url = 'employees/'), name='index'),
    url(r'^skills/', views.SkillsView.as_view(), name='skills'),
    url(r'^employees/$', views.EmployeesView.as_view(), name='employees'),
    url(r'^candidates/$', views.CandidatesView.as_view(), name='candidates'),
    url(r'^employees/(?P<pk>[0-9]+)/$', views.EmployeeDetailView.as_view(), name='employeedetailspage'),
    url(r'^candidates/(?P<pk>[0-9]+)/$', views.CandidateDetailView.as_view(), name='candidatedetailspage'),
    url(r'^employeesjson/', views.EmployeesJSONView.as_view(), name='employeesjson'),
    url(r'^candidatesjsonview/', views.CandidatesJSONView.as_view(), name='candidatesjson'),
    url(r'^employeesadvancedjson/', views.EmployeesAdvancedJSONView.as_view(), name='employeesadvancedjson'),
    url(r'^candidatesadvancedjson/', views.CandidatesAdvancedJSONView.as_view(), name='candidatesadvancedjson'),
    url(r'^employeescomplexjson/', views.EmployeesComplexJSONView.as_view(), name='employeescomplexjson'),
    url(r'^candidatescomplexjson/', views.CandidateComplexJSONView.as_view(), name='candidatescomplexjson'),
    url(r'^details/(?P<pk>[0-9]+)/$', views.EmployeeJSONDetailView.as_view(), name='employeedetails'),
    url(r'^cdetails/(?P<pk>[0-9]+)/$', views.CandidateJSONDetailView.as_view(), name='candidatedetails'),
    url(r'^details/$', RedirectView.as_view(pattern_name="employees"), name='employeedetailsredirect'),
    url(r'^cdetails/$', RedirectView.as_view(pattern_name="candidates"), name='candidatedetailsredirect'),
    url(r'^hire/(?P<candidate_id>[0-9]+)/$', views.HireCandidateView.as_view(), name='hire'),
    url(r'^hire/$', RedirectView.as_view(pattern_name="hire"), name='hireredirect'),
    url(r'^interviews/$', views.InterviewListView.as_view(), name='interviews'),
    url(r'^interviews/(?P<candidate_id>[0-9]+)/$', views.InterviewListView.as_view(), name='interviews'),
    url(r'^einterviews/(?P<employee_id>[0-9]+)/$', views.EmployeeInterviewListView.as_view(), name='einterviews'),
    url(r'^interview/$', views.InterviewDetailView.as_view(), name='interviewplug'),
    url(r'^interview/(?P<pk>[0-9]+)/$', views.InterviewDetailView.as_view(), name='interview'),
    url(r'^einterview/(?P<pk>[0-9]+)/$', views.EmployeeInterviewDetailView.as_view(), name='einterview'),
    url(r'^reviews/(?P<employee_id>[0-9]+)/$', views.ReviewListView.as_view(), name='reviews'),
    url(r'^review/(?P<pk>[0-9]+)/$', views.ReviewDetailView.as_view(), name='review'),
]

skillsearch/models.py
from django.db import models
from django.core.files.base import ContentFile
from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator
from djmoney.models.fields import MoneyField
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image
from io import BytesIO
from .validators import validate_file_extension
import os

class Skills(models.Model):
    class Meta:
        verbose_name_plural = "skills"
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class Team(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class Position (models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class ProfileBase(models.Model):
    '''
    Parent abstract class for Employees and Candidate classes
    '''
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    birthday = models.DateField(blank=True, null=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField('Phone', validators=[phone_regex], max_length=15, blank=True)
    skype = models.CharField(max_length=30, blank=True)
    picture = models.ImageField(upload_to='./', default='./plug.png')
    thumbnail = models.ImageField(upload_to='./', editable=False, default='./plug.png')
    cv = models.FileField(upload_to='./cv/', validators=[validate_file_extension], blank=True, verbose_name='CV')
    added_by = models.ForeignKey(User, blank=True, null=True)
    #Social
    facebook = models.URLField(blank=True, max_length=128)
    linkedin = models.URLField(blank=True, max_length=128)
    twitter = models.URLField(blank=True, max_length=128)

    class Meta:
        abstract = 'True'

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    def save_default(self, *args, **kwargs):
        super(ProfileBase, self).save(*args, **kwargs)

    def save(self, *args, **kwargs):
        super(ProfileBase, self).save(*args, **kwargs)
        #Check whether default picture is set in order to prevent converting during every save
        if str(self.picture.name) != str(self.thumbnail.name) and '_thumb' not in self.thumbnail.name:
            if not self.make_thumbnail():
                raise Exception('Could not create thumbnail - is the file type valid?')

    def file_icon(self):
        extension = self.cv.name.split('.')[-1]
        if extension == 'pdf':
            return 'fa-file-pdf-o'
        elif extension in ['doc', 'docx']:
            return 'fa-file-word-o'
        return 'fa-file-file-o'

    def make_thumbnail(self):
        '''
        Create and save the thumbnail for the photo (simple resize with PIL).
        '''

        try:
            image = Image.open(self.picture)
        except:
            return False

        image.thumbnail((self.picture.width, settings.THUMB_SIZE), Image.ANTIALIAS)

        # Path to save to, name, and extension
        thumb_name, thumb_extension = os.path.splitext(self.picture.name)
        thumb_extension = thumb_extension.lower()

        thumb_filename = thumb_name + '_thumb' + thumb_extension
        if thumb_extension in ['.jpg', '.jpeg']:
            FTYPE = 'JPEG'
        elif thumb_extension == '.gif':
            FTYPE = 'GIF'
        elif thumb_extension == '.png':
            FTYPE = 'PNG'
        else:
            return False  # Unrecognized file type

        temp_thumb = BytesIO()
        # image.save(settings.MEDIA_ROOT + '/' + thumb_filename, FTYPE)
        image.save(temp_thumb, FTYPE)
        temp_thumb.seek(0)

        self.thumbnail.save('./' + thumb_filename, ContentFile(temp_thumb.read()), save=False)
        temp_thumb.close()
        self.save_default()
        return True

#Employees

class Employees(ProfileBase):
    class Meta:
        verbose_name_plural = "employees"

    pemail = models.EmailField('Personal Email', max_length=100, blank=True)
    cemail = models.EmailField('Corporate Email', max_length=100, blank=True)
    position = models.ManyToManyField(Position)
    active = models.BooleanField(default=True)
    compliance = models.ForeignKey('ComplianceResult', null=True)
    teams = models.ManyToManyField(Team)
    skillset = models.ManyToManyField(Skills, through='EmployeeSkills', related_name='employees')

    def serialize(self):
        skillset = self.skillset.all()
        skills = list()
        levels = self.get_levels()
        for index, skill in enumerate(skillset):
            skills.append({'name': skill.name, 'level': levels[index], 'id': skill.id})
            skillset[index].level = levels[index]
        return {
            'id': self.id,
            'first_name': self.first_name,
            'last_name': self.last_name,
            'birthday': self.birthday.strftime('%b. %d, %Y') if self.birthday else self.birthday,
            'phone': self.phone_number,
            'pemail': self.pemail,
            'cemail': self.cemail,
            'skype': self.skype,
            'linkedin': self.linkedin,
            'facebook': self.facebook,
            'twitter': self.twitter,
            'active': self.active,
            'picture':  self.thumbnail.url,
            'teams': self.teams.all(),
            'positions': self.position.all(),
            'cv': self.cv.url if self.cv else '',
            'cvicon': self.file_icon() if self.cv else '',
            'skillset': skills,
            'added_by': self.added_by.first_name + ' ' + self.added_by.last_name if self.added_by else '',
            'compliance': self.compliance if self.compliance else '',
        }

    def get_levels(self):
        #Seems like not a good idea, probably need to remake
        employeeskill = EmployeeSkills.objects.filter(employees__exact=self.id)
        return [s.level for s in employeeskill]

class ComplianceResult(models.Model):
    COLORS = (
        ('primary', 'Primary (blue)'),
        ('secondary', 'Secondary (grey)'),
        ('success', 'Success (green)'),
        ('danger', 'Danger (red)'),
        ('warning', 'Warning (yellow)'),
        ('info', 'Info (light blue)'),
        ('light', 'Light (light grey)'),
        ('dark', 'Dark (almost black)'),
        ('white', 'White'),
    )

    name = models.CharField(max_length=30)
    color = models.CharField(max_length=10, choices=COLORS, default='success')

    def __str__(self):
        return self.name

class EmployeeSkills(models.Model):
    class Meta:
        verbose_name_plural = "Skills"
    employees = models.ForeignKey(Employees)
    skills = models.ForeignKey(Skills)
    level = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(10)], default=0)

class Review(models.Model):
    employee = models.ForeignKey(Employees)
    date = models.DateField(blank=True, null=True)
    responsilities_feedback = models.TextField(max_length=4000)
    responsilities_promises = models.TextField(max_length=4000)
    team_feedback = models.TextField(max_length=4000)
    team_promises = models.TextField(max_length=4000)
    office_feedback = models.TextField(max_length=4000)
    office_promises = models.TextField(max_length=4000)
    other_feedback = models.TextField(max_length=4000)
    other_promises = models.TextField(max_length=4000)

    def serialize(self):
        return {
            'id': self.id,
            'date': self.date.strftime('%b. %d, %Y') if self.date else self.date,
            'responsilities_feedback': self.responsilities_feedback,
            'responsilities_promises': self.responsilities_promises,
            'team_feedback': self.team_feedback,
            'team_promises': self.team_promises,
            'office_feedback': self.office_feedback,
            'office_promises': self.office_promises,
            'other_feedback': self.other_feedback,
            'other_promises': self.other_promises,
            'link': self.get_link()
        }

    def get_link(self):
        return reverse('skillsearch:review', args=(self.id,))

    def __str__(self):
        return self.employee.first_name + ' ' + self.employee.last_name

class Salary(models.Model):
    class Meta:
        verbose_name_plural = "salary"
    employee = models.ForeignKey(Employees)
    current_salary = MoneyField(max_digits=10, decimal_places=2, default_currency='EUR')
    desired_salary = MoneyField(max_digits=10, decimal_places=2, default_currency='EUR')

    def __str__(self):
        return self.employee.first_name + ' ' + self.employee.last_name

    def serialize(self):
        return {
            'id': self.id,
            'current_salary': self.current_salary,
            'desired_salary': self.desired_salary,
        }

#Candidates

class Candidate(ProfileBase):
    email = models.EmailField(max_length=100, blank=True)
    skillset = models.ManyToManyField(Skills, through='CandidateSkills', related_name='candidates')

    def serialize(self):
        skillset = self.skillset.all()
        skills = list()
        levels = self.get_levels()
        for index, skill in enumerate(skillset):
            skills.append({'name': skill.name, 'level': levels[index], 'id': skill.id})
            skillset[index].level = levels[index]
        return {
            'id': self.id,
            'first_name': self.first_name,
            'last_name': self.last_name,
            'birthday': self.birthday,
            'phone': self.phone_number,
            'email': self.email,
            'skype': self.skype,
            'linkedin': self.linkedin,
            'facebook': self.facebook,
            'twitter': self.twitter,
            'picture':  self.thumbnail.url,
            'skillset': skills,

skillsearch/templates/skillsearch/base.html
{% extends "hrmain/base.html" %}
{% load static %}

{% block style %}
    <link href="{% static 'skillsearch/css/style.css' %}" rel="stylesheet">
{% endblock %}

skillsearch/templates/skillsearch/candidate_details.html
{% extends "skillsearch/profile.html" %}
{% load static %}

{% block body %}
    {% include 'skillsearch/candidate_profile_body.html' %}
{% endblock %}

{% block custom_js %}
    <script>
        function custom_js () {
            $('#btn-hire').popover({
                html: true,
                content: $('#hire-popover').html(),
                trigger: 'focus'
            });
        }
    </script>
{% endblock %}

skillsearch/templates/skillsearch/candidate_profile_body.html
{% load static %}
<div class='container-fluid'>
    <div class="row" id="body-template-row">
        <div class="col" id="profile-card-container" align="left">
            <div class="card" style="width: 20rem;">
                <img class="profile-picture-img rounded" id="profile-picture" src="{% if candidate.picture %}{% get_media_prefix %}{{ candidate.picture }}{% endif %}" alt="Card image cap">
                <div class="card-body card-body-details">
                <h4 class="empty-tab" id="employee-details-name" align="center">{{ candidate.first_name }} {{ candidate.last_name }}</h4>
                </div>
            </div>
        </div>
        <div class="col" id="profile-container">
            <ul class="nav nav-tabs" id=candidate-profile-tab role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="candidate-profile-tab-button" href="#profile" data-toggle="tab" role="tab" aria-controls="profile" aria-selected="true">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="candidate-interviews-tab-button" href="#interviews" data-toggle="tab" role="tab" aria-controls="interviews" aria-selected="false">Interviews</a>
                </li>
                {% if perms.skillsearch.change_candidate %}
                    <li class="nav-item">
                        <a class="nav-link" id="candidate-control-tab-button" href="#control" data-toggle="tab" role="tab" aria-controls="control" aria-selected="false">Control</a>
                    </li>
                {% endif %}
            </ul>
            <div class="tab-content">

                <div class="tab-pane fade show active employee-profile rounded-bottom" id="profile" role="tabpanel" aria-labelledby="candidate-profile-tab-button">
                    <div class="stand-out-left">
                        <dl class="row">
                            <!-- Salary -->
                            {% if perms.skillsearch.add_candidatesalary and  perms.skillsearch.change_candidatesalary and perms.skillsearch.delete_candidatesalary %}
                                <dt class="col-md-1" id="salary-header"><i class="fa fa-money" aria-hidden="true" data-toggle="tooltip" data-placement="left" title="Salary"></i></dt>
                                <dd class="col-md-11" id="salary-tab">
                                    <div class="salary empty-tab" id="cand-salary">{{ candidatesalary.salary }}</div>
                                </dd>
                            {% endif %}

                            <dt class="col-md-1" id="birthday-header"><i class="fa fa-birthday-cake" aria-hidden="true" data-toggle="tooltip" data-placement="left" title="Birthday"></i></dt>
                            <dd class="col-md-11 empty-tab" id="birthday-tab">
                                {% if candidate.birthday %}
                                    {{ candidate.birthday }}
                                {% endif %}
                            </dd>

                            <dt class="col-md-1" id="phone-header"><i class="fa fa-phone-square" aria-hidden="true" data-toggle="tooltip" data-placement="left" title="Phone"></i></dt>
                            <dd class="col-md-11 empty-tab" id="phone-tab">
                                {{ candidate.phone_number }}
                            </dd>

                            <dt class="col-md-1" id="email-header"><i class="fa fa-envelope-o" aria-hidden="true" data-toggle="tooltip" data-placement="left" title="Email"></i></dt>
                            <dd class="col-md-11 empty-tab" id="email-tab">
                                {{ candidate.email }}
                            </dd>

                            <dt class="col-md-1" id="skype-header"><i class="fa fa-skype" aria-hidden="true" data-toggle="tooltip" data-placement="left" title="Skype"></i></dt>
                            <dd class="col-md-11 empty-tab" id="skype-tab">
                                {{ candidate.skype }}
                            </dd>

                            <dt class="col-md-1" id="cv-header"><i class="fa fa-id-badge" aria-hidden="true" data-toggle="tooltip" data-placement="left" title="CV"></i></dt>
                            <dd class="col-md-11 empty-tab" id="cv-tab">
                                {% if candidate.cv %}
                                    <i class="fa {{ candidate.file_icon }}" aria-hidden="true"></i> <a href="{% get_media_prefix %}{{ candidate.cv }}">Download</a>
                                {% endif %}
                            </dd>

                            <dt class="col-md-1"><i class="fa fa-wrench" aria-hidden="true" data-toggle="tooltip" data-placement="left" title="Skills"></i></dt>
                            <dd class="col-md-11" id="skillset-tab">
                                {% for skill in candidate.serialize.skillset %}
                                    {{ skill.name }}
                                    <div class="progress">
                                        <div class="progress-bar progress-bar-striped" role="progressbar" style="width: {{ skill.level }}0%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100">{{ skill.level }}</div>
                                    </div>
                                {% endfor %}
                            </dd>
                            <footer class="blockquote-footer">Added by: <cite title="Source Title" id="added-by-tab" class="empty-tab">{{ candidate.added_by.first_name }} {{ candidate.added_by.last_name }}</cite></footer>
                        </dl>
                    </div>
                </div>

                {% include "skillsearch/interviews_modal.html" %}

                {% if perms.skillsearch.change_candidate %}
                    <div class="tab-pane fade employee-profile rounded-bottom" id="control" role="tabpanel" aria-labelledby="candidate-control-tab-button">
                        <div class="stand-out-left">
                            <dl class="row">
                                <dt class="col-sm-3">Control</dt>
                                <dd class="col-sm-9" id="control-section">
                                    {% if perms.skillsearch.delete_candidate and  perms.skillsearch.add_employees%}
                                        <button type="button" class="btn btn-success btn-hire" id="btn-hire" data-toggle="popover" data-placement="right">Hire</button>
                                    {% endif %}
                                </dd>
                            </dl>
                        </div>
                    </div>

                    <div id="hire-popover" class="hide">
                        <h5 class="text-center">Are you sure you want to hire this person?</h5>
                        <p class="text-center text-danger">This action cannot be reverted.</p>
                        <div class="hire-buttons" align="center">
                            <form action="{{ hire_url }}" method="get" class="form-inline" id="hire-form">
                                <button type="submit" class="btn btn-success btn-hire-yes mx-auto" id="btn-hire-yes">Yes, hire</button>
                                <button type="button" class="btn btn-danger btn-hire-no mx-auto" id="btn-hire-no">No, CANCEL</button>
                            </form>
                        </div>
                    </div>

                {% endif %}

            </div>
        </div>
    </div>
</div>

skillsearch/templates/skillsearch/candidates.html
{% extends "skillsearch/skillsearch.html" %}

{% block destination %}
    '{% url 'skillsearch:candidatesjson' %}'
{% endblock %}

{% block advanced_destination %}
    '{% url 'skillsearch:candidatesadvancedjson' %}'
{% endblock %}

{% block complex_destination %}
    '{% url 'skillsearch:candidatescomplexjson' %}'
{% endblock %}

{% block base_destination %}
    '{% url 'skillsearch:candidatesjson' %}'
{% endblock %}

{% block details_destination %}
    "{% url 'skillsearch:candidatedetailsredirect' %}"
{% endblock %}

{% block include_body %}
    {% include 'skillsearch/candidate_profile_body.html' %}
{% endblock %}

{% block custom_js_onload %}
    custom_onload(employee_id)
{% endblock %}

{% block custom_js %}
    <script>
        function custom_onload() {
            $('#btn-hire').popover({
                html: true,
                content: $('#hire-popover').html(),
                trigger: 'focus'
            });
            $('#btn-hire').click(function() {
                $(".popover-body").find('#hire-form').attr("action", "{% url 'skillsearch:hireredirect' %}" + employee_id + "/")
            })
        }
    </script>
{% endblock %}

skillsearch/templates/skillsearch/employee_details.html
{% extends "skillsearch/profile.html" %}
{% load static %}

{% block body %}
    {% include 'skillsearch/employee_profile_body.html' %}
{% endblock %}

{% block custom_js %}
    <script>
        function custom_js () {
            return
        }
    </script>
{% endblock %}

skillsearch/templates/skillsearch/employees.html
{% extends "skillsearch/skillsearch.html" %}

{% block destination %}
    '{% url 'skillsearch:employeesjson' %}'
{% endblock %}

{% block advanced_destination %}
    '{% url 'skillsearch:employeesadvancedjson' %}'
{% endblock %}

{% block complex_destination %}
    '{% url 'skillsearch:employeescomplexjson' %}'
{% endblock %}

{% block base_destination %}
    '{% url 'skillsearch:employeesjson' %}'
{% endblock %}

{% block details_destination %}
    "{% url 'skillsearch:employeedetailsredirect' %}"
{% endblock %}

{% block include_body %}
    {% include 'skillsearch/employee_profile_body.html' %}
{% endblock %}

{% block additional_search_options %}
    <option value="team">Team</option>
    <option value="position">Position</option>
{% endblock %}

skillsearch/templates/skillsearch/interview.html
{% extends "skillsearch/base.html" %}

{% block body %}
    <div class="container-fluid col-sm-9 col-md-10">
        <div class="row justify-content-center interview-col">
            <div class="col-md-8 border rounded">
                <div class="row interview-row justify-content-between">
                    <div class="col-md-4">
                        <div class="interview-photo-frame border rounded">
                            <img class="interview-photo-img" src="{{ profile.thumbnail.url}}">
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="row interview-row">
                            <div class="col-md-12" align="left">
                                <h3>{{ profile }}</h3>
                            </div>
                        </div>
                        <div class="row interview-row">
                            <div class="col-md-12">
                                <dl class="row border border-right-0 border-left-0 border-top-0">
                                    <dt class="col-sm-5 d-nomargin">Date</dt>
                                    <dd class="col-sm-7 d-nomargin">
                                        {{ interview.date }}
                                    </dd>
                                    <dt class="col-sm-5 d-nomargin">Result</dt>
                                    <dd class="col-sm-7 d-nomargin text-{{ interview.result.color }}">
                                        {{ interview.result }}
                                    </dd>
                                    <dt class="col-sm-5 d-nomargin">Teams</dt>
                                    <dd class="col-sm-7 d-nomargin">
                                        {% for team in interview.teams.all %}
                                            {{ team }}
                                        {% endfor %}
                                    </dd>
                                    <dt class="col-sm-5 d-nomargin">Interviewers</dt>
                                    <dd class="col-sm-7 d-nomargin">
                                        {% for interviewer in interview.interviewers.all %}
                                            {% if forloop.counter != interview.interviewers.count %}
                                                <a class="interviewer-link" data-content="<img class='interviewer-img rounded' src='{{ interviewer.thumbnail.url }}'>" href="{% url 'skillsearch:employeedetailspage' interviewer.id %}">{{ interviewer }}</a>,
                                            {% else %}
                                                <a class="interviewer-link" data-content="<img class='interviewer-img rounded' src='{{ interviewer.thumbnail.url }}'>" href="{% url 'skillsearch:employeedetailspage' interviewer.id %}">{{ interviewer }}</a>
                                            {% endif %}
                                        {% endfor %}
                                    </dd>
                                    <dt class="col-sm-5 d-nomargin">Short description</dt>
                                    <dd class="col-sm-7 d-nomargin">
                                        {{ interview.short_description }}
                                    </dd>
                                </dl>
                                <h5><b>Description</b></h5>
                                <p>{{ interview.description }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        window.onload = function() {
            $('.interviewer-link').popover({
                trigger: 'hover',
                html: true,
{#                template: '<div class="popover" role="tooltip"><div class="arrow"></div><h3 class="popover-header"></h3><div class="popover-body"></div></div>',#}
                placement: 'bottom'
            })
        }
    </script>
{% endblock %}

skillsearch/templates/skillsearch/interviews.html
{% extends "skillsearch/base.html" %}

{% block body %}
    <div class="container-fluid col-sm-9 col-md-10">

        <div class="body-template base-body">
            <h1>{% if profile %}{{ profile }}'s {% else %}All {% endif %}Interviews</h1>
        </div>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Date</th>
                    <th scope="col">Result</th>
                    <th scope="col">Short Description</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for interview in interviews %}
                    <tr>
                        <th scope="row">{{ interview.date }}</th>
                        <td class="text-{{ interview.result.color }}">{{ interview.result }}</td>
                        <td>{{ interview.short_description }}</td>
                        <td><a href="{{ interview.get_link }}">Open>></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div><!-- /.container -->
{% endblock %}

skillsearch/templates/skillsearch/interviews_modal.html
<div class="tab-pane fade employee-profile rounded-bottom" id="interviews" role="tabpanel" aria-labelledby="candidate-interviews-tab-button">
    <div class="interview-container empty-tab">
        {% for interview in interviews %}
            <div class="col-md-12 interview-frame rounded border border-default">
                <div class="col-md-6 d-inline-block">
                    <dl class="row dl-interview">
                        <dt class="col-sm-5 d-nomargin">Date</dt>
                        <dd class="col-sm-7 d-nomargin">
                            {{ interview.date }}
                        </dd>
                        <dt class="col-sm-5 d-nomargin">Result</dt>
                        <dd class="col-sm-7 d-nomargin text-{{ interview.result.color }}">
                            {{ interview.result }}
                        </dd>
                        <dt class="col-sm-5 d-nomargin">Short description</dt>
                        <dd class="col-sm-7 d-nomargin">
                            {{ interview.short_description }}
                        </dd>
                    </dl>
                </div>
                <div class="col-md-6 d-inline-block interview-right" align="right">
                    <div class="col-md-12">

                    </div>
                    <div class="col-md-12 interview-open" align="bottom">
                        <a href="{{ interview.get_link }}">Open>></a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="interview-button">
        <button {% if profile_id %}onclick="window.open('{{ interviews_link }}', '_blank')" {% endif %}type="button" class="btn btn-secondary btn-lg btn-block btn-all-interviews">Show all</button>
    </div>
</div>

skillsearch/templates/skillsearch/skills.html
{% extends "hrmain/base.html" %}

{% block body %}
    {% if skills %}
        <div class="container-fluid">
            <div class="body-template">
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Skill name</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for skill in skills %}
                            <tr>
                                <th scope="row">{{ skill.id }}</th>
                                <td>{{ skill.name }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% endif %}

{% endblock %}